# Generated by Django 2.1.2 on 2018-10-20 12:54

from django.db import migrations, models
import django.db.models.deletion
import twitter_stream.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', twitter_stream.fields.PositiveBigAutoField(primary_key=True, serialize=False)),
                ('tweet_id', models.BigIntegerField()),
                ('text', models.CharField(max_length=250)),
                ('truncated', models.BooleanField(default=False)),
                ('lang', models.CharField(blank=True, default=None, max_length=9, null=True)),
                ('user_id', models.BigIntegerField()),
                ('user_screen_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=150)),
                ('user_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('user_utc_offset', models.IntegerField(blank=True, default=None, null=True)),
                ('user_time_zone', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('filter_level', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('user_geo_enabled', models.BooleanField(default=False)),
                ('user_location', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('favorite_count', models.PositiveIntegerField(blank=True, null=True)),
                ('retweet_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user_followers_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user_friends_count', models.PositiveIntegerField(blank=True, null=True)),
                ('in_reply_to_status_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('retweeted_status_id', models.BigIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
                'swappable': 'TWITTER_STREAM_TWEET_MODEL',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=250)),
                ('app_name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('api_key', models.CharField(max_length=250)),
                ('api_secret', models.CharField(max_length=250)),
                ('access_token', models.CharField(max_length=250)),
                ('access_token_secret', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FilterTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.CharField(max_length=250)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeout_seconds', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('last_heartbeat', models.DateTimeField()),
                ('hostname', models.CharField(max_length=250)),
                ('process_id', models.PositiveIntegerField()),
                ('memory_usage', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('STOPPED', 'Stopped')], default='WAITING', max_length=10)),
                ('tweet_rate', models.FloatField(default=0)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
                ('keys', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_stream.ApiKey')),
            ],
        ),
    ]
